#!/bin/bash
EXTENSION_NAME="eZ oracle"
EXTENSION_IDENTIFIER="ezoracle"
EXTENSION_SUMMARY="Adds support for Oracle database in eZ publish"
EXTENSION_LICENSE="eZ Proprietary License"
EXTENSION_VERSION="1.6"
EXTENSION_PUBLISH_VERSION="3.9.5"
EXTENSION_ARCHIVE_NAME="ezoracle"
EXTENSION_PHP_VERSION="4.4"

EXTENSION_FILTER_FILES="INSTALL README FAQ"
