#!/bin/bash
EXTENSION_NAME="eZ Oracle"
EXTENSION_IDENTIFIER="ezoracle"
EXTENSION_SUMMARY="Adds support for Oracle database in eZ Publish"
EXTENSION_LICENSE="GNU General Public License v2.0"
EXTENSION_VERSION="1.8.1"
EXTENSION_PUBLISH_VERSION="4.0.1"
EXTENSION_ARCHIVE_NAME="ezoracle"
EXTENSION_PHP_VERSION="5.1"

EXTENSION_FILTER_FILES="INSTALL README FAQ"
