#!/bin/bash
EXTENSION_NAME="eZ Oracle"
EXTENSION_IDENTIFIER="ezoracle"
EXTENSION_SUMMARY="Adds support for Oracle database in eZ Publish"
EXTENSION_LICENSE="GNU General Public License v2.0"
EXTENSION_VERSION="2.1.0"
EXTENSION_PUBLISH_VERSION="4.?"
EXTENSION_ARCHIVE_NAME="ezoracle"
EXTENSION_PHP_VERSION="5.?"

EXTENSION_FILTER_FILES="INSTALL README FAQ"
